### ISSUE TITLE
Update MorePage to Match Figma Design with improved Usability.

### ISSUE THREAD

**Issue by rcAsironman** [oss-slu/lrda_mobile#203]
**Description**

The current MorePage is filled with text, making it confusing for users. Update the MorePage to align with the Figma design for a more user-friendly experience.

**Current MorePage:**
<div> <img width="231" alt="Screenshot 2024-11-19 at 11 22 53 AM" src="https://github.com/user-attachments/assets/f4f3f35e-93ad-4fe9-a9d1-729bf6e288ee"> <img width="218" alt="Screenshot 2024-11-19 at 11 23 09 AM" src="https://github.com/user-attachments/assets/a3bc29b6-4678-46e1-8610-5c5e918767d7"> </div>

**Expected MorePage:**
<div> <img width="218" alt="Screenshot 2024-11-19 at 11 18 25 AM" src="https://github.com/user-attachments/assets/5e22f904-8817-4028-9b2e-60de01c37d47"> <img width="240" alt="Screenshot 2024-11-19 at 11 18 35 AM" src="https://github.com/user-attachments/assets/1445add6-92ea-4962-9334-1e0d8a9bb58a"> </div>

**Note: No changes are required for the bottomTabBar.**

**Figma URL:**
https://www.figma.com/proto/aT6Bxx1QLkyMqN9EnWUw7G/Untitled?page-id=0%3A1&node-id=70-1600&node-type=frame&viewport=539%2C-6891%2C1.1&t=OjX4IFbhJq6fllHc-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=1%3A3&show-proto-sidebar=1

**Tasks**

- [x] Locate the MorePage and update its code to match the Figma design.
- [x] Write responsive code that adjusts seamlessly across all devices.
- [x] Implement test cases for the updated MorePage.
- [x] Run the app on both emulator/simulator and physical devices to verify functionality.

**Acceptance Criteria**

- [x] The MorePage matches the design shown in the Figma.
- [x] All test cases pass successfully.
- [x] The app runs smoothly on both emulator/simulator and physical devices.
